version: '3'
services:
  rabbitmq:
    image: rabbitmq:3 
    ports:
      - 5672:5672
#    logging:
#      driver: none
  meme-classifier:
    image: meme-classifier
    environment:
      - PORT=5000
      - LOG_LEVEL=INFO
    command: python server.py
  consumer:
    image: consumer
    environment:
      - SIDECAR_HOST=meme-classifier
      - SIDECAR_PORT=5000
      - RABBITMQ_HOST=rabbitmq
      - QUEUE_NAME=tasks
      - LOG_LEVEL=INFO
    command: python main.py
    restart: on-failure
    depends_on:
      - rabbitmq
